### ISSUE TITLE
Support for multiple API Keys

### ISSUE THREAD

**Issue by XInTheDark** [EvanZhouDev/gemini-ai#14]
Hi again! Would it be beneficial to implement support for multiple API Keys? Instead of inputting one key, support can be added for passing an array of API Keys during initialisation. In the API, it could try to make a request using each API Key in order; if for example the key isn't valid or if a rate limit is reached, then it goes on to try the next key.

Reason: The main downside to using gemini-1.5-pro is simply the low rate limits (only 50 requests per day, pretty low for normal use). If we can input 5 API keys for example (this is quite feasible as most people have quite a few google accounts), the limit becomes 250 which is much better and suitable for daily use.

I believe this isn't against Gemini ToS, as I didn't see anything about forbidding multiple google accounts. Please feel free to close this if it in fact is.

**Comment by EvanZhouDev** [comment]
My original thought is that this is out of scope. It has been made that you can make individual Gemini object so that you can do this on your own. However, if you believe that this is in scope, please let me know your argument.

**Comment by XInTheDark** [comment]
Indeed, I also agree that the extra complexity isn't worth it, and currently it's pretty simple for the user to implement this anyways. Closing :)
