### ISSUE TITLE
I am using CommonJS and i get error (I read the FAQ)

### ISSUE THREAD

**Issue by MZRCode** [EvanZhouDev/gemini-ai#19]
I'm using **CommonJS** and i am getting the error '**Gemini is not a constructor**' even though i am doing it the way you mentioned at the bottom of the **FAQ**. I'm putting the necessary SS below. **Have a nice day.**

![geminiAI](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/ef8df387-d5a7-4784-9682-3e7f88245c24)
![question](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/10145e9a-c871-492f-9037-453d68b28708)

**Comment by EvanZhouDev** [comment]
Sorry, I must have made a small error when typing out that code snippet. It should be fixed now. The callback takes the entire export object, and doesn't automatically give the default. Thus, all you have to do is destructure the callback for `default` inline and rename it to `Gemini` again. Something like this should work:

```javascript
import("gemini-ai").then(async ({ default: Gemini }) => {
	let gemini = new Gemini(API_KEY);
});
```

I have also updated the FAQ as not to confuse future readers.
https://github.com/EvanZhouDev/gemini-ai?tab=readme-ov-file#how-do-i-use-gemini-ai-in-a-cjs-environment

Thank you for pointing this out!

**Comment by MZRCode** [comment]
Hello, **after** this edit **i am getting an error again**. I don't understand what exactly this error is. I am attaching the necessary SS below. **Have a nice day.**

![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/5ac0fb66-2972-4284-8abf-7a3c72472fea)
![image](https://github.com/EvanZhouDev/gemini-ai/assets/87870017/8950964d-5f31-4773-9e5d-0064bf3a4d35)
