### ISSUE TITLE
how to apply an http proxy ?

### ISSUE THREAD

**Issue by xhawk18** [EvanZhouDev/gemini-ai#2]

**Comment by iwestlin** [comment]
也许可以参考这两条：
https://github.com/google/generative-ai-js/issues/29#issuecomment-1866246513
https://github.com/google/generative-ai-js/pull/38/files

**Comment by EvanZhouDev** [comment]
@xhawk18 @iwestlin Feature coming in 1.1, hopefully to be released soon. Thank you for your patience!

**Comment by EvanZhouDev** [comment]
Added in Gemini AI 1.1... check it out [here](https://github.com/EvanZhouDev/gemini-ai/tree/v1.1.0?tab=readme-ov-file#proxy-support)!
